name: Keywords Service

env:
  POSTGRES_USER: test
  POSTGRES_PASSWORD: password
  POSTGRES_DB: keyword_test_db
  PGUSER: test
  PGPASSWORD: postgres
  PGDATABASE: keyword_test_db


on: [push]

jobs:
      
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports: 
          - 5432:5432

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        python setup.py sdist
        pip install dist/*
        unzip nltk_data/archive/stopwords.zip -d nltk_data/corpora
        unzip nltk_data/archive/wordnet.zip -d nltk_data/corpora
    
    - name: Initialize database 
      timeout-minutes: 2
      env: 
        PGHOST: localhost
        PGPORT: 5432
    
      run:
        psql -f ./schema.sql

    - name: Test with pytest
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        NLTK_DATA: ./nltk_data
        FLASK_SECRET_KEY: test

      run: |
        pytest

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run:
        docker build -t keywords_service .